apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
      matchLabels:
        app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        env:
          - name: CLICKHOUSE_USER
            value: "default"
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: clickhouse-auth
                key: password
          - name: CLICKHOUSE_SERVER_MEMORY_USAGE_TO_RAM_RATIO
            value: "0.9"
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 8123
        - containerPort: 9000
        volumeMounts:
        - name: ck-data
          mountPath: /var/lib/clickhouse
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: ck-data
        hostPath:
          path: /opt/clickhouse
          type: DirectoryOrCreate
      - name: init-scripts
        configMap:
          name: clickhouse-init-scripts