apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: "templated-by-parent"
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.13.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://templated-by-parent"
    namespace: cert-manager