apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:shuaizhang1997/my-k3s.git
    targetRevision: master
    path: gitOps/infra/image-updater
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true