apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:shuaizhang1997/my-k3s.git
    targetRevision: master
    path: gitOps/infra/argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true