apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor
  namespace: argocd
spec:
  project: infra-project
  source:
    repoURL: git@github.com:shuaizhang1997/my-k3s.git
    targetRevision: master
    path: gitOps/infra/monitor
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true