apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-chart
  namespace: argocd
spec:
  project: infra-project
  source:
    repoURL: git@github.com:shuaizhang1997/my-k3s.git
    targetRevision: master
    path: gitOps/infra/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true