apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
  labels:
    name: argo-rollouts
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
    istio-injection: enabled