apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: "templated-by-parent"
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.28.3
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://templated-by-parent
    namespace: istio-system