apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  project: infra-project
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.28.3
    helm:
      values: |
        global:
          hub: gcr.io/istio-release
          tag: 1.20.3
        meshConfig:
          accessLogFile: /dev/stdout
          extensionProviders:
            - name: otel-collector
              otel:
                service: otel-collector.monitoring.svc.cluster.local
                port: 4317
          defaultProviders:
            tracing: [otel-collector]
            accessLogging: [otel-collector]
        pilot:
          traceSampling: 50.0
  
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated: {prune: true, selfHeal: true}