apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
  namespace: monitoring
spec:
  hosts:
  - grafana.k3s.shuaizhang.net
  gateways:
  - istio-system/infra-gateway
  http:
  - route:
    - destination:
        host: grafana
        port:
          number: 80