apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
spec:
  accessLogging:
    - providers:
        - name: otel-log-provider
  tracing:
    - providers:
        - name: otel-collector
      randomSamplingPercentage: 100