apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-non-prod
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: sealed-secrets
            path: gitOps/clusters/non-prod/infra/sealed-secrets
            wave: "-10"
          - appName: istio-base
            path: gitOps/clusters/non-prod/infra/istio-base
            wave: "-5"
            destNamespace: "istio-system"
          - appName: cert-manager
            path: gitOps/clusters/non-prod/infra/cert-manager
            wave: "-4"
          - appName: issuer
            path: gitOps/clusters/non-prod/infra/issuer
            wave: "-3"
          - appName: istiod
            path: gitOps/clusters/non-prod/infra/istiod
            wave: "0"
          - appName: istio-gateway
            path: gitOps/clusters/non-prod/infra/istio-gateway
            wave: "5"
          - appName: argo-rollouts
            path: gitOps/clusters/non-prod/infra/argo-rollouts
            wave: "10"
          - appName: argo-workflows
            path: gitOps/clusters/non-prod/infra/argo-workflows
            wave: "10"
          - appName: argo-workflows
            path: gitOps/clusters/non-prod/infra/image-updater
            wave: "10"
          - appName: monitoring
            path: gitOps/clusters/non-prod/infra/monitoring
            wave: "20"
  template:
    metadata:
      name: 'non-prod-{{appName}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:shuaizhang1997/my-k3s.git
        targetRevision: master
        path: '{{path}}'
      kustomize:
          buildOptions: "--enable-helm"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true